---
title: "Public data: domestic dogs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(fig.align = "center", out.width = "70%", 
                      fig.width = 16, fig.asp = 0.7, error = TRUE)
options(width = 85)
```

```{r, eval=FALSE}
bed <- "http://www.datadryad.com/bitstream/handle/10255/dryad.104774/cornell_canine.bed"
bim <- "http://www.datadryad.com/bitstream/handle/10255/dryad.104773/cornell_canine.bim"
fam <- "http://www.datadryad.com/bitstream/handle/10255/dryad.104772/cornell_canine.fam"
lapply(c(bed, bim, fam), function(url) {
  download.file(url, destfile = paste0("backingfiles/", basename(url)))
})
```

```{r}
plink <- download_plink()
snp_plinkQC("backingfiles/cornell_canine", 
            plink.path = plink,
            maf = 0.05,
            geno = 0,
            hwe = 1e-10,
            autosome.only = TRUE,
            extra.options = "--dog")
```


```{r}
system.time(
  rds <- snp_readBed("backingfiles/cornell_canine_QC.bed", "backingfiles/dogs")
)
system.time(
  bigsnp <- snp_attach("backingfiles/dogs.rds")
)
```

```{r}
G <- bigsnp$genotypes
sum(big_counts(G)[4, ])
```


